import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

import { api } from "../utils/api";
//
// admin_ghost
// PUkRvvh5MooCiJQd

const Home: NextPage = () => {
  const postUser = api.user.post.useMutation();

  const [email, setEmail] = useState("");

  const handleSetEmail = (e: React.ChangeEvent<HTMLInputElement>) => {
    setEmail((_) => e.target.value);
  };

  const handleCreateUser = () => {
    postUser.mutate({ email });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input placeholder="Email" onChange={handleSetEmail} />
        <button onClick={handleCreateUser}>Create</button>
      </div>
    </>
  );
};

export default Home;
